### ISSUE TITLE
Our products - product category : Layout of the ordered and unordered list is not consistent with the design.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Buster-s-Baby-Warehouse#102]
![image](https://cloud.githubusercontent.com/assets/11186313/7021197/e43a6bf6-dd51-11e4-8a8a-87ed6b332243.png)

**Comment by ramoncebudigital** [comment]
In category description you added raw text, the output would be automatically in paragraph(<p>) cuz this is not a wysiwyg editor. So if you want to add text's same as wysiwyg editor you will need to include the tags(<ul>,<ol> etc...) in the category description.

**Comment by roseliesromeo** [comment]
This is not invalid.
It would be unlikely for users to include codes in the description to achieve the desired layout.

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/7083187/67aa134c-df91-11e4-93ac-7dc3e99d16d5.png)
