### ISSUE TITLE
Single print page:  There is no space gap between rows of thumbnails.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Buster-s-Baby-Warehouse#113]
![image](https://cloud.githubusercontent.com/assets/11186313/7038416/060e59f8-dde4-11e4-80b1-48c1b69296b9.png)

**Comment by roseliesromeo** [comment]
Can we clarify if we are going to display all thumbnails in rows (like how it was) or use carousel like in the single page?

Seems like you are not sure of how it is going to be implemented.

**Comment by ramoncebudigital** [comment]
I'm using the carousel, so if the thumbnails reach it's limits to 8 images, the carousel will enable.
