### ISSUE TITLE
Our products single page:  Page slug is inconsistent with the page title.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Buster-s-Baby-Warehouse#123]
![image](https://cloud.githubusercontent.com/assets/11186313/7064511/cc0b1d96-dee1-11e4-9506-edca7ea3ca8f.png)

**Comment by ramoncebudigital** [comment]
yes, because you changed the product title, but didn't changed url.

**Comment by roseliesromeo** [comment]
Are users supposed to change url/slug?

**Comment by ramoncebudigital** [comment]
This is the way wordpress is.
