### ISSUE TITLE
Our Products single page:  Can't we remove the + icon from the sidebar single product list?

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Buster-s-Baby-Warehouse#16]
![image](https://cloud.githubusercontent.com/assets/11186313/6842046/f884a37a-d3cd-11e4-9088-b74f08924dcb.png)

**Comment by ramoncebudigital** [comment]
I just followed what is in the design specs,
same with the News page.
so what do you think? 
remove it or not? 
![screenshot_1](https://cloud.githubusercontent.com/assets/11186436/6911197/dea78592-d78f-11e4-93b4-44b327c96aac.png)
