### ISSUE TITLE
Admin - Pages: Page template has not been created.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Buster-s-Baby-Warehouse#18]
![image](https://cloud.githubusercontent.com/assets/11186313/6842292/eaef15bc-d3d0-11e4-9e1c-16f1e1fbde40.png)

**Comment by ramoncebudigital** [comment]
Our products template ca be set in woocommerce products tab.
![screenshot_1](https://cloud.githubusercontent.com/assets/11186436/6911393/b6fc91ec-d792-11e4-9baf-2b711029c199.png)

**Comment by roseliesromeo** [comment]
There should be template set for each page.

As per standard:

Instead of naming the PHP template similar to the page’s slug, ensure that the page has also set it as it’s own template and follows the naming convention: template-page-name.php

This is to ensure that the page will continue to use the said PHP template even if the client has accidentally changed the page’s slug.

**Comment by roseliesromeo** [comment]
Still has no page template.

**Comment by ramoncebudigital** [comment]
Leoman said that woocom is exempted on this.

**Comment by roseliesromeo** [comment]
Apply page template to all pages except WooCommerce.

**Comment by ramoncebudigital** [comment]
Yes, but the main issue here is about Our Product page.  So this issue is invalid.
Anyways added page templates to all pages except woocom.

**Comment by roseliesromeo** [comment]
The main issue here is Admin - Pages: Page template.
