### ISSUE TITLE
Our Products single page - W3C: 16 Errors, 1 warning(s)

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Buster-s-Baby-Warehouse#32]
http://validator.w3.org/check?verbose=1&uri=http://busters-baby-warehouse.stage.titanweb.com.au/products/product-subcategory/sample-product-4-2/

**Comment by ramoncebudigital** [comment]
link to view the product 
http://busters-baby-warehouse.stage.titanweb.com.au/our-products/sample-product-4-2/

**Comment by roseliesromeo** [comment]
Still got error.
