### ISSUE TITLE
Footer section:  Height of the section container doesn't match the design provided.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Buster-s-Baby-Warehouse#48]
![image](https://cloud.githubusercontent.com/assets/11186313/6864667/97ed98c8-d49f-11e4-9767-abc2a5d6bfb1.png)

**Comment by ramoncebudigital** [comment]
height is the same with the design on my end.

![screenshot_2](https://cloud.githubusercontent.com/assets/11186436/6913097/df7b339c-d7ad-11e4-94f8-565c443dfdb9.png)
