### ISSUE TITLE
Footer section:  Background color of the footer section is different from the design.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Buster-s-Baby-Warehouse#49]
![image](https://cloud.githubusercontent.com/assets/11186313/6864693/e614ce9a-d49f-11e4-9abe-a86779e47bb9.png)

**Comment by ramoncebudigital** [comment]
background color is the same with the design specs on my end.

![screenshot_2](https://cloud.githubusercontent.com/assets/11186436/6913097/df7b339c-d7ad-11e4-94f8-565c443dfdb9.png)
