### ISSUE TITLE
Suppliers section:  Navigation arrow is not vertically centered.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Buster-s-Baby-Warehouse#98]
iPad air (landscape)

![image](https://cloud.githubusercontent.com/assets/11186313/6892986/a9d958ca-d6fb-11e4-9c05-6d974af635c3.png)

**Comment by roseliesromeo** [comment]
Still not centered.

**Comment by ramoncebudigital** [comment]
working on my end.

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/7061956/cd1d8cf8-deca-11e4-8eb6-afcfc28204fb.png)

**Comment by roseliesromeo** [comment]
Refer to bug #108
