### ISSUE TITLE
News single page: Featured image is not centered.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Buster-s-Baby-Warehouse#99]
iTouch 5

![image](https://cloud.githubusercontent.com/assets/11186313/7038165/06d05cfa-dde0-11e4-9dda-5f44a8c96ee5.png)

**Comment by ramoncebudigital** [comment]
I don't see any featured image in your screenshot.

**Comment by roseliesromeo** [comment]
I updated screenshot above.
